# Generated by Django 4.0.5 on 2022-06-15 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_tag_app', '0002_tag_user_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tag',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_title', to='user_tag_app.tag'),
        ),
    ]
