# Generated by Django 4.0.5 on 2022-06-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tag_app', '0003_alter_user_tag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tag',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
