# Generated by Django 4.0.5 on 2022-06-15 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tag_app', '0004_alter_user_tag_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tag',
            name='timestamp',
            field=models.DateTimeField(default=datetime.timezone),
        ),
    ]
