# Generated by Django 4.0.5 on 2022-06-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tag_app', '0007_user_tag_timestamp1_alter_user_tag_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_tag',
            name='timestamp1',
        ),
        migrations.AlterField(
            model_name='user_tag',
            name='timestamp',
            field=models.IntegerField(default=1655353503.742532, max_length=200),
        ),
    ]
