# Generated by Django 4.0.5 on 2022-06-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tag_app', '0009_user_tag_short_text_alter_user_tag_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_tag',
            old_name='short_text',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='user_tag',
            name='timestamp',
            field=models.IntegerField(default=1655354026.550061, max_length=200),
        ),
    ]
